name: Build package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: main

    - name: Build
      run: ./build.sh

    - name: Store package
      uses: actions/upload-artifact@v2
      with:
        name: emacs-pgtk
        path: ./packages/emacs-pgtk_*.deb
